checkout-path: &checkout-path
  checkout-path: /go/src/github.com/palantir/pkg

version: 2.1

orbs:
  go: palantir/go@0.0.14
  godel: palantir/godel@0.0.14

workflows:
  version: 2
  verify-test:
    jobs:
      # bearertoken
      - godel/verify:
          name: bearertoken-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/bearertoken
      - godel/test:
          name: bearertoken-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/bearertoken
      - godel/test:
          name: bearertoken-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/bearertoken

      # binary
      - godel/verify:
          name: binary-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/binary
      - godel/test:
          name: binary-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/binary
      - godel/test:
          name: binary-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/binary
