checkout-path: &checkout-path
  checkout-path: /go/src/github.com/palantir/pkg

version: 2.1

orbs:
  go: palantir/go@0.0.14
  godel: palantir/godel@0.0.14

workflows:
  version: 2
  verify-test:
    jobs:
      # bearertoken
      - godel/verify:
          name: bearertoken-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/bearertoken
      - godel/test:
          name: bearertoken-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/bearertoken
      - godel/test:
          name: bearertoken-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/bearertoken

      # binary
      - godel/verify:
          name: binary-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/binary
      - godel/test:
          name: binary-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/binary
      - godel/test:
          name: binary-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/binary

      # bytesbuffers
      - godel/verify:
          name: bytesbuffers-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/bytesbuffers
      - godel/test:
          name: bytesbuffers-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/bytesbuffers
      - godel/test:
          name: bytesbuffers-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/bytesbuffers

      # cli
      - godel/verify:
          name: cli-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/cli
      - godel/test:
          name: cli-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/cli
      - godel/test:
          name: cli-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/cli

      # cobracli
      - godel/verify:
          name: cobracli-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/cobracli
      - godel/test:
          name: cobracli-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/cobracli
      - godel/test:
          name: cobracli-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/cobracli

      # datetime
      - godel/verify:
          name: datetime-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/datetime
      - godel/test:
          name: datetime-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/datetime
      - godel/test:
          name: datetime-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/datetime

      # gittest
      - godel/verify:
          name: gittest-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/gittest
      - godel/test:
          name: gittest-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/gittest
      - godel/test:
          name: gittest-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/gittest

      # httpclient
      - godel/verify:
          name: httpclient-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/httpclient
      - godel/test:
          name: httpclient-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/httpclient
      - godel/test:
          name: httpclient-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/httpclient

      # httpserver
      - godel/verify:
          name: httpserver-verify
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/httpserver
      - godel/test:
          name: httpserver-test-go-1.13
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.13.4
            owner-repo: palantir/pkg/httpserver
      - godel/test:
          name: httpserver-test-go-1.12
          <<: *checkout-path
          executor:
            name: go/golang
            version: 1.12.13
            owner-repo: palantir/pkg/httpserver
